//import './globals.css'
import type { Metadata } from "next";
//import { Inter } from 'next/font/google'

import DrawerAppBar from "@/app/components/appbar";
import * as React from "react";
import  Box  from "@mui/material/Box";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        

          <DrawerAppBar />
        

        {children}
      </body>
    </html>
  );
}
